name: Deploy to EC2

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      rollback_commit:
        description: "Commit SHA to rollback to (leave empty for latest)"
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          
          cd ~/webapps/helloreact
          
          # Backup current build
          if [ -d "build" ]; then
            mv build build_backup
          fi
          
          # Clone latest version
          if [[ -n "${{ github.event.inputs.rollback_commit }}" ]]; then
            git fetch
            git checkout ${{ github.event.inputs.rollback_commit }}
          else
            git checkout master
            git pull origin master
          fi
          
          # Install dependencies and build React app
          npm install
          npm run build
          
          # Serve with Nginx
          sudo cp -r build /var/www/html/helloreact
          sudo systemctl restart nginx
          
          # Health Check
          sleep 10
          if ! curl -s --max-time 5 http://localhost | grep -q "React App"; then
            echo "Health check failed! Rolling back..."
            rm -rf build
            mv build_backup build
            sudo systemctl restart nginx
          else
            echo "Deployment successful!"
          fi
        EOF
